# Generated by Django 5.0.1 on 2024-02-04 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateField(default=datetime.datetime(2024, 2, 5, 19, 39, 59, 211015, tzinfo=datetime.timezone.utc))),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
